### ISSUE TITLE
test expected "Test Prompt"

### ISSUE THREAD

**Issue by div-donis** [learn-co-curriculum/react-hooks-fetch-crud-lab#1]
Received this error message when completing the Question Form component, but this is not part of the deliverables or the pre-coded react code. 

"Unable to find an element with the text: /Test Prompt/g. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible."

**Comment by graciemcguire** [comment]
Hey @div-donis ! One of the deliverables in this lab is to send the form data from the API when the form is
submitted, the data from the API contains a key 'prompt' that you can use to solve this. 

If you need further help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!

**Comment by div-donis** [comment]
Thank you for your response. My instructor is actually who suggested me to comment here to find some resolution. When I console log my formData, it does indeed show  
{
      id: 3,
      prompt: 'Test Prompt',
      answers: [ 'Test Answer 1', 'Test Answer 2', '', '' ],
      correctIndex: '1'
    }
as one of the objects sent to the API, which is then passed to the input element's value attribute. However, I still get that error message.
